[package]
name = "uniffi-bindgen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uniffi = { git = "https://github.com/mgeisler/uniffi-rs", branch = "uniffi", features = ["cli"] }
