[package]
name = "mls-platform-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mls-rs = { git = "https://github.com/mgeisler/mls-rs", branch = "uniffi", features = ["sqlcipher-bundled"] }
mls-rs-crypto-rustcrypto = { git = "https://github.com/mgeisler/mls-rs", branch = "uniffi" }
mls-rs-provider-sqlite = { git = "https://github.com/mgeisler/mls-rs", branch = "uniffi" }
hex = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["alloc", "derive", "rc"] }
bincode = "1.3"
sha2 = "0.10.8"
thiserror = "1"
