[package]
name = "mls-platform-api"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"

[dependencies]
mls-rs =  {git = "https://github.com/beurdouche/mls-rs", rev = "9b6065e3f53ad7ed2a24998da3cd0a30a1b264e6", features = ["sqlcipher-bundled", "serde"] }
mls-rs-crypto-nss = {git = "https://github.com/beurdouche/mls-rs", rev = "9b6065e3f53ad7ed2a24998da3cd0a30a1b264e6"}
mls-rs-provider-sqlite = {git = "https://github.com/beurdouche/mls-rs", rev = "9b6065e3f53ad7ed2a24998da3cd0a30a1b264e6"}
hex = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["alloc", "derive", "rc"] }
bincode = "1.3"
sha2 = "0.10.8"
thiserror = "1"
serde_json = "1.0.114"
