[package]
name = "mls-platform-api"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"

[dependencies]
mls-rs =  {git = "https://github.com/beurdouche/mls-rs", rev = "ba784fb2ecd4832683ece9c62f00572914372cb3", features = ["sqlcipher-bundled", "serde"] }
mls-rs-crypto-nss = {git = "https://github.com/beurdouche/mls-rs", rev = "ba784fb2ecd4832683ece9c62f00572914372cb3"}
mls-rs-provider-sqlite = {git = "https://github.com/beurdouche/mls-rs", rev = "ba784fb2ecd4832683ece9c62f00572914372cb3"}
hex = { version = "0.4", features = ["serde"] }
serde = { version = "1.0", features = ["alloc", "derive", "rc"] }
bincode = "1.3"
sha2 = "0.10.8"
thiserror = "1"
serde_json = "1.0.114"
